language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.3

    # The SDK version used to compile your project
    - android-30

licenses:
 - android-sdk-license-.+

branches:
  only:
  - develop

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./scripts/check.sh